name: test-workflow
on:
  push:
    branches: [main]

jobs:
  job-1:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Print date
        run: echo $(date)

  job-2:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Print date
        run: echo $(date)

  job-3:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Print date
        run: echo $(date)

  job-4:
    runs-on: ${{ matrix.os }}
    needs: [job-1, job-2, job-3]
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Print date
        run: echo $(date)
